# Generated by Django 2.2 on 2019-06-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('view_num', models.IntegerField()),
                ('like_num', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=16)),
                ('regist_time', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('avatar', models.ImageField(blank=True, height_field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True), null=True, upload_to='Img/avatar/', width_field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True))),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noti_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.User')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fld_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blogApp.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='blogApp.User')),
            ],
            options={
                'db_table': 'Follow',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('favourite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.User')),
            ],
            options={
                'db_table': 'Favourite',
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.User')),
            ],
            options={
                'db_table': 'Cookie',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=600)),
                ('time', models.DateTimeField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.User')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('blog_tag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Blog')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Tag')),
            ],
            options={
                'db_table': 'BlogTag',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.User'),
        ),
        migrations.RunSQL('alter table User auto_increment = 100000'),
        migrations.RunSQL('alter table Admin auto_increment = 10000'),
    ]
