# Generated by Django 2.2 on 2019-06-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blogtag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cookie',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='fld_user_id',
            new_name='fld_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
    ]
