# Generated by Django 2.2 on 2019-06-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20190630_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cate_id',
            new_name='cate',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_id',
            new_name='user',
        ),
    ]
