# Generated by Django 2.2 on 2019-07-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20190630_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1000001, on_delete=django.db.models.deletion.CASCADE, to='blogApp.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
