# Generated by Django 2.2.2 on 2019-07-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20190701_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
