# Generated by Django 2.2.2 on 2019-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
